// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'card.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Card _$CardFromJson(Map<String, dynamic> json) => Card(
      id: (json['id'] as num).toInt(),
      slug: json['slug'] as String,
      title: json['title'] as String,
      publicUrl: json['publicUrl'] as String,
      bio: json['bio'] as String?,
      isPublic: json['isPublic'] as bool,
      viewsCount: (json['viewsCount'] as num).toInt(),
      walletPassUrl: json['walletPassUrl'] as String?,
      allowPayment: json['allowPayment'] as bool,
      nfcEnabled: json['nfcEnabled'] as bool,
      qrCodeUrl: json['qrCodeUrl'] as String?,
      totalShared: (json['totalShared'] as num).toInt(),
      totalLeads: (json['totalLeads'] as num).toInt(),
      theme: $enumDecode(_$CardThemeEnumMap, json['theme']),
      createdAt: DateTime.parse(json['createdAt'] as String),
      updatedAt: DateTime.parse(json['updatedAt'] as String),
      email: json['email'] as String,
      firstName: json['firstName'] as String?,
      lastName: json['lastName'] as String?,
      phone: json['phone'] as String?,
      company: json['company'] as String?,
      position: json['position'] as String?,
      website: json['website'] as String?,
      linkedinUrl: json['linkedinUrl'] as String?,
      twitterUrl: json['twitterUrl'] as String?,
      instagramUrl: json['instagramUrl'] as String?,
      address: json['address'] as String?,
      city: json['city'] as String?,
      country: json['country'] as String?,
      avatar: json['avatar'] as String?,
      companyLogo: json['companyLogo'] as String?,
      userId: (json['userId'] as num).toInt(),
      subscription: json['subscription'],
    );

Map<String, dynamic> _$CardToJson(Card instance) => <String, dynamic>{
      'id': instance.id,
      'slug': instance.slug,
      'title': instance.title,
      'publicUrl': instance.publicUrl,
      'bio': instance.bio,
      'isPublic': instance.isPublic,
      'viewsCount': instance.viewsCount,
      'walletPassUrl': instance.walletPassUrl,
      'allowPayment': instance.allowPayment,
      'nfcEnabled': instance.nfcEnabled,
      'qrCodeUrl': instance.qrCodeUrl,
      'totalShared': instance.totalShared,
      'totalLeads': instance.totalLeads,
      'theme': _$CardThemeEnumMap[instance.theme]!,
      'createdAt': instance.createdAt.toIso8601String(),
      'updatedAt': instance.updatedAt.toIso8601String(),
      'email': instance.email,
      'firstName': instance.firstName,
      'lastName': instance.lastName,
      'phone': instance.phone,
      'company': instance.company,
      'position': instance.position,
      'website': instance.website,
      'linkedinUrl': instance.linkedinUrl,
      'twitterUrl': instance.twitterUrl,
      'instagramUrl': instance.instagramUrl,
      'address': instance.address,
      'city': instance.city,
      'country': instance.country,
      'avatar': instance.avatar,
      'companyLogo': instance.companyLogo,
      'userId': instance.userId,
      'subscription': instance.subscription,
    };

const _$CardThemeEnumMap = {
  CardTheme.purple: 'purple',
  CardTheme.blue: 'blue',
  CardTheme.teal: 'teal',
  CardTheme.green: 'green',
  CardTheme.orange: 'orange',
  CardTheme.red: 'red',
  CardTheme.pink: 'pink',
  CardTheme.indigo: 'indigo',
  CardTheme.emerald: 'emerald',
  CardTheme.amber: 'amber',
};
