# mobile/pubspec.yaml (VERSION COMPLÈTE CORRIGÉE)
name: showme
description: Application de cartes de visite digitales professionnelles
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Navigation
  cupertino_icons: ^1.0.6
  go_router: ^12.1.3
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # Network & API
  dio: ^5.3.2
  retrofit: ^4.0.3
  json_annotation: ^4.9.0
  
  # Storage & State
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # NFC & Hardware
  nfc_manager: ^3.3.0
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  camera: ^0.10.5+5
  
  # Location & Maps
  geolocator: ^10.1.0
  permission_handler: ^11.0.1
  google_maps_flutter: ^2.5.0
  
  # Payments
  flutter_stripe: ^10.1.1
  
  # Utils
  intl: ^0.18.1
  uuid: ^4.1.0
  image_picker: ^1.0.4
  url_launcher: ^6.2.1
  
  # Apple Wallet & File handling
  path_provider: ^2.1.1
  archive: ^3.4.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.7
  retrofit_generator: ^8.0.4
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  
  # Linting
  flutter_lints: ^3.0.1
  
  # Testing
  mockito: ^5.4.2

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/